### ISSUE TITLE
[Question]CLI ?

### ISSUE THREAD

**Issue by thenoobtester** [ggtylerr/divolt-desktop#12]
Is there anyway to use this as a command line? I would like to be able to post a message to a bot and get a reply back. If not with this, is there any such client?

Thank you for this app and your help

**Comment by ggtylerr** [comment]
Sorry for the late response, GH notifications are broken for some reason.

This is a GUI only app. I don't think there's any clients that let you do that, you'll probably have to make a custom script for that. If you just want TUI, there's [an archived project called Revolt.Cli](https://github.com/Jan0660/Revolt.Cli), but AFAIK you'll have to rebuild it specifically for Divolt.
