### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by kpcenti** [ggtylerr/divolt-desktop#13]
I'm getting network errors and the app never loads 
![image](https://user-images.githubusercontent.com/10696951/225779426-3d88fbc4-78c7-4f4d-a221-5d1d4bffc14c.png)

on v1.0.6-d1.2.1

**Comment by ggtylerr** [comment]
Can you try clearing cache? (Taskbar icon -> Clear Cache) If that doesn't work, can you send a screenshot of the console (CTRL+SHIFT+I -> Console)

**Comment by kpcenti** [comment]
That worked. Not sure what happened
