### ISSUE TITLE
Cannot log-in.  Getting a database error.

### ISSUE THREAD

**Issue by klepp0906** [ggtylerr/divolt-desktop#14]
Went afk and came back disconnected.  tried the usual suspects and upon attempting to log in i'm being met with 

![image](https://user-images.githubusercontent.com/10392920/227005192-f5f4c54b-8a3e-4201-b1d6-12e9a351cbe6.png)

I assume its not a client issue but a server issue?

ftr it changed to 

![image](https://user-images.githubusercontent.com/10392920/227035310-330e910e-3fa7-481b-b38f-6bc2ed5a45bc.png)

so perhaps being addressed.

**Comment by ggtylerr** [comment]
This is a server issue, not related to the app. Thank you for informing me though, I'll let the server admins know about this.

**Comment by taskylizard** [comment]
Closing as this has since been fixed.
