### ISSUE TITLE
Linux: Crash when choosing restart from tray icon

### ISSUE THREAD

**Issue by 9thyear2** [ggtylerr/divolt-desktop#16]
results in this:

Error Window: 
![Screenshot from 2023-08-29 13-15-49](https://github.com/fmhy/divolt-desktop/assets/29149297/8d5a1deb-7d41-420e-a318-0007a9b63add)

Divolt Window: 
![Screenshot from 2023-08-29 13-15-53](https://github.com/fmhy/divolt-desktop/assets/29149297/deba4a09-62d5-4d49-b6d2-c69135195045)

**Comment by ggtylerr** [comment]
Sorry for the late response, been pretty busy. This has been fixed in [v1.0.6-d1.2.2.](https://github.com/fmhy/divolt-desktop/releases/tag/v1.0.6-d1.2.2)
