### ISSUE TITLE
Unable to import .json file for Theme overrides.

### ISSUE THREAD

**Issue by despaler** [ggtylerr/divolt-desktop#17]
I understand this is a fork of the main Revolt program, but it would still be nice to be able to use my own theme overrides for this program.

**Comment by ggtylerr** [comment]
Sorry for the late response, been busy with other stuff. Adding this specifically (exporting and importing json FILE themes) would require changing the website code itself and thus is outside the scope of this fork. That being said, it seems like using the clipboard still works, so you'll still be able to use your themes from Revolt:

https://github.com/fmhy/divolt-desktop/assets/28498877/9446ac4a-4bd7-48b4-9a7e-aea7e8e88ef8

(right side is Divolt - note the slightly outdated API version)
