### ISSUE TITLE
Divolt desktop application doesn't log chat activity anymore

### ISSUE THREAD

**Issue by Daoet** [ggtylerr/divolt-desktop#19]
I've been using Divolt for a while, but today I noticed the chat seems off. I saw there is no recent chat activity for at least half 15h in the general discussion chat, up to a couple of days in other chats. but on Discord all those chats after the last sent message popped up as it normally should. 

The chats that I send isn't searchable in the Discord. I noticed there was one user who posted just recently after I noticed this problem, I tried to search for his message in the Discord but it didn't show up. I suspect he might have the same problem as I do.

I switched to the portable Windows version via this page https://github.com/fmhy/divolt-desktop/releases/tag/v1.0.6-d1.2.2 
and upgraded the application, then rebooted my machine. Lots of other features were fixed or improved on my end, but the chat is yet to become active again (just like prior, when I used the Desktop setup version). 

I don't really know what's wrong, but I need help. I don't really use discord to talk, just checking messages is all.

I use a Windows 10 Home 22H2 (OSBuld 19045.3693).

**Comment by ggtylerr** [comment]
Not an issue with Divolt, that's just the bridge bot not working @rhld16

**Comment by Daoet** [comment]
What should I do next, in order to resolve this "bridge bot" issue? I doubt the majority of people are having the same problem. 

Since it's bridge related I wanna note there's an additional weird thing I've been made aware of, which might have to do with the issue; in the past, I've heard from others my profile has been marked as  "BOT". Iirc, those people have given me a discord invite in order to be seen as bridge. That never happened, but I was able to see all the messages (incl. my own) from Divolt in Discord, until now.

**Comment by ggtylerr** [comment]
You can't do anything about it, just notify the server staff that it's down.

How it works is the bot posts your message for you on discord, and vice versa. On Divolt it's easier to hide, but on Discord, it pops up as the bot sending that.
