### ISSUE TITLE
Tray icon and Desktop settings are missing in built Mac versions

### ISSUE THREAD

**Issue by ggtylerr** [ggtylerr/divolt-desktop#2]
_Note: This has been a known issue for a while now and I have no idea why I didn't make this yet. Sorry._

On MacOS, the tray icon is invisible and desktop settings are completely missing. This leads to users usually unable to open the app after minimizing / closing (due to quit to tray) and, due to the invisible icon, they usually default to force quitting via activity monitor.

**This issue is only present in built versions.** For some reason, this is not present when running from source code. This means the issue lies within the initial build process _(and somehow does not occur in the original app.)_

**Comment by 0xCUB3** [comment]
I am also experiencing this issue

**Comment by ggtylerr** [comment]
Update: The Windows version is also missing a tray icon, although the desktop settings are present. Not sure about the Linux version.

I was gonna try an updated release structure for MacOS that should've solved the problem, but now that it's done for Windows and the bug is present, I'm not sure it would work. The problem is that I have no idea what's actually causing it - whether it's something on my end, on divolt's, on the building library, etc.

**Comment by ggtylerr** [comment]
This issue should be resolved with [v1.0.6-d1.2.1,](https://github.com/ggtylerr/divolt-desktop/releases/tag/v1.0.6-d1.2.1) although Desktop Settings may or may not work (during testing I have not seen it go away at all, so I'm not sure what actually caused the problem, although I know it existed at one point.)

I'll be leaving this issue pinned for now - please comment here if you're still having this problem.
