### ISSUE TITLE
Text Size Options

### ISSUE THREAD

**Issue by kpcenti** [ggtylerr/divolt-desktop#3]
Is it possible to suggest a text size options? 

The default text is rather small

**Comment by ggtylerr** [comment]
This would be an upstream issue, as Revolt itself does not support this, and Divolt is just a version of Revolt being hosted. (This app is also just a browser with some extra flare, much like Discord's app.) In fact, someone already made an issue for this in the web client repo: [Revite #727](https://github.com/revoltchat/revite/issues/727)

There is, however, a workaround that you can use with the CSS override. Go into settings, appearance, advanced, custom CSS, and paste this in:
```css
* { --text-size: 14px; }
```
Alternatively you can zoom in and out using `CTRL +` and `CTRL -`
