### ISSUE TITLE
The desktop app just shows a black screen.

### ISSUE THREAD

**Issue by Offert4324** [ggtylerr/divolt-desktop#9]
The desktop app just shows a black screen, and nothing happens even if I wait.
It works perfectly well on Chrome, and I also checked that the original app works fine.

Chrome
![화면 캡처 2022-09-14 213245](https://user-images.githubusercontent.com/104715700/190156641-eb79ca99-e898-4b8e-8c74-8c540a3200e6.png)

App
![화면 캡처 2022-09-14 212541](https://user-images.githubusercontent.com/104715700/190156686-a13deb26-1932-4b6e-b9ef-181a965a95ce.png)

**Comment by fabriguzden** [comment]
This is the error
GET https://divolt.xyz/assets/main.2d37164d.js net::ERR_QUIC_PROTOCOL_ERROR 200
I also have problems accessing, even in the web version from google chrome, edge and firefox
#8

**Comment by fabriguzden** [comment]
![image](https://user-images.githubusercontent.com/27593140/190217114-3358832c-4297-4d0b-a985-65c6c2e569d0.png)

**Comment by shas737** [comment]
same problem here

**Comment by shas737** [comment]
update: its fixed for me now

**Comment by ggtylerr** [comment]
Shoutouts to GH for not giving me any notifications.

@Offert4324, in the app can you open up console (CTRL+SHIFT+I then Console at the top) and paste the full log somewhere? (maybe https://paste.fo/ )

@fabriguzden this is a separate issue, and one that's on Divolt's side, not the app. If you're able to, try using a VPN in another location (someone mentioned using mullvad in finland)

@lucid73 do you know if you changed anything to make it work?

**Comment by shas737** [comment]
> @lucid73 do you know if you changed anything to make it work?

nothing, it gave me the same error yesterday, today I woke up and it opened normally without any errors

**Comment by Offert4324** [comment]
> @Offert4324, in the app can you open up console (CTRL+SHIFT+I then Console at the top) and paste the full log somewhere? (maybe https://paste.fo/ )

Now it works fine for me, too. If something has changed, I think Divolt has changed something. Do you need the full log anyways?

**Comment by ggtylerr** [comment]
I think I know the issue, and if it's the case, then I'm sorry @fabriguzden for saying that it was a different issue.

After talking with the folks who run Divolt, it turns out the proxy server's storage was full, and thus no new users could access the site. This problem has since been resolved.
